cookbook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recipes/', include('recipes.urls')),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path

from . import views

app_name = 'recipes'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<str:recipe_id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('save/', views.save, name='save'),
]

users/urls.py
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('',views.loginpage,name='loginpage'),
    path('dologin/',views.dologin, name='dologin'),
    path('register/',views.register, name='register'),
    path('saveuser/', views.saveuser, name='saveuser'),
    path('logoutpage/', views.logoutpage, name='logoutpage'),
    path("contact/", views.contact_form, name="contact_form"),
]

recipes/models.py
from django.db import models


# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=200)
    created_date = models.DateTimeField(auto_now_add=True,null=True, blank=True)
    ingredients = models.CharField(max_length=200)
    process = models.TextField()
    recipe_img = models.ImageField(upload_to='images/',null=True)

    def __str__(self):
        return self.name

    # def get_recipe_img(self):
    #     if self.recipe_img:
    #         return self.recipe_img.url
    #     else:
    #         return "/media/images/1.jpg"

users/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)
# Create your models here.

class MyUserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, mobile_no, date_of_birth, age, country, password=None):
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email), # Normalize the email address by lowercasing the domain part of it.
            first_name=first_name,
            last_name=last_name,
            mobile_no=mobile_no,
            date_of_birth=date_of_birth,
            age=age,
            country=country,
            )
        user.set_password(password)
        user.save(using=self._db) # takes its default value is specified in settings.py
        return user

    def create_superuser(self, email, first_name, last_name, mobile_no, date_of_birth, age, country, password=None):
        user = self.create_user(
            email,
            password=password,
            first_name=first_name,
            last_name=last_name,
            mobile_no=mobile_no,
            age=age,
            date_of_birth=date_of_birth,
            country=country,
        )
        user.is_admin=True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(
        verbose_name='first name',
        max_length=255,
    )
    last_name = models.CharField(
        verbose_name='last name',
        max_length=255,
    )
    mobile_no = models.IntegerField(
        verbose_name='mobile no',
    )
    date_of_birth = models.DateField()
    age = models.IntegerField()
    country = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    # when you are changing authentication from username to email, you need to write below line. It means authentication happens through email field.
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['date_of_birth', 'country', 'first_name', 'last_name', 'mobile_no', 'age']

    def __str__(self):
        return self.email

    #https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#django.contrib.auth.backends.ModelBackend.has_perm
    # Uses get_all_permissions() to check if user_obj has the permission string perm. Returns False if the user is not is_active.
    def has_perm(self, perm, obj=None):
        return True

    # Returns whether the user_obj has any permissions on the app app_label.
    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

recipes/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Recipe
# Create your views here.
from django.urls import reverse



@login_required(login_url='/users/')
def index(request):
    # print("index function")
    name_list = Recipe.objects.order_by('-created_date')
    # print(name_list)
    return render(request, 'recipes/index.html', {'name_list':name_list})

@login_required(login_url='/users/')
def detail(request,recipe_id):
    recipe = Recipe.objects.filter(id=recipe_id)
    return render(request, 'recipes/detail.html', {'recipe':recipe})

@login_required(login_url='/users/')
def create(request):
    # recipe = Recipe(name=request.POST.get('name'), ingredients=request.POST.get('ingredients'),
    #                 process=request.POST.get('process'))
    # recipe.save()
    return render(request, 'recipes/create.html')
    # return HttpResponseRedirect('/recipes/create')
    # try:
    #     # recipe = Recipe(name=request.POST.get('name'),ingredients=request.POST.get('ingredients'),process=request.POST.get('process'))
    #     recipe = Recipe(name=request.POST.get('name',''),ingredients=request.POST.get('ingredients',''),process=request.POST.get('process',''))
    #     recipe.save()
    # except(KeyError,Recipe.DoesNotExist):
    #     return render(request,'recipes/create.html',{'error_message': "You didn't enter any value"})
    # # return render(request, 'recipes/create.html', {'recipe': recipe})
    # return HttpResponseRedirect('')


def save(request):
    print(request.POST)
    print(request.FILES)
    recipe = Recipe(name=request.POST.get('name'), ingredients=request.POST.get('ingredients'),
                    process=request.POST.get('process'),recipe_img=request.FILES['recipe_img'])
    recipe.save()
    return HttpResponseRedirect('/recipes')

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

from .form import ContactForm
from .models import MyUser, MyUserManager
from django.contrib.auth.models import User


# Create your views here.
def loginpage(request):
    return render(request, 'users/login.html')


def dologin(request):
    email = request.POST['email']
    password = request.POST['password']
    user = authenticate(request, email=email, password=password)
    if user is not None:
        # import pdb;pdb.set_trace()
        login(request, user)
        return HttpResponseRedirect('/recipes')
    else:
        return render(request, 'users/login.html',{'message':"Email and Password are not valid."})
        # return HttpResponseRedirect('/users/')
        # return HttpResponseRedirect('/users/' + "Username and Password are not valid.")


def register(request):
    return render(request, 'users/register.html')


def saveuser(request):
    MyUser.objects.create_user(first_name=request.POST.get('first_name'),last_name=request.POST.get('last_name'), email=request.POST.get('email'),
                password=request.POST.get('password'), mobile_no=request.POST.get('mobile_no'), date_of_birth=request.POST.get('date_of_birth'), age=request.POST.get('age'), country=request.POST.get('country'))
    # user.set_password(user.password) # convert plain password into hashed
    # user.save()
    return HttpResponseRedirect('/users')

def logoutpage(request):
    logout(request)
    return HttpResponseRedirect('/users/')

def contact_form(request):
    if request.method == "GET":
        return render(request, "users/contact_form.html",{"form":ContactForm()})
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            cc_myself = form.cleaned_data["cc_myself"]
            return render(request, "users/contact_form.html",{"form":ContactForm()})
        else:
            return render(request, "users/contact_form.html", {"form": ContactForm(),"errors":form.errors})

recipes/templates/recipes/create.html
<div style="text-align: right">
<a href="{% url 'users:logoutpage' %}">Logout</a>
</div>
<div style="text-align: center">
<h1>Create Recipe</h1>
</div>
{% if error_message %}
   <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'recipes:save' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <label for="name">Name:</label><br>
    <input type="text" id="name" name="name"><br>
    <label for="ingredients">Ingredients:</label><br>
    <input type="text" id="ingredients" name="ingredients"><br>
    <label for="process">Process:</label><br>
    <input type="text" id="process" name="process"><br>
    <label for="recipe_img">Recipe Image:</label><br>
    <input type="file" id="recipe_img" name="recipe_img"><br><br>
    <input type="submit" value="Create">
</form>

recipes/templates/recipes/detail.html
<div style="text-align: right">
<a href="{% url 'users:logoutpage' %}">Logout</a>
</div>
<div style="text-align: center">
<h1>Detail Recipe</h1>
</div>

{% for r in recipe %}
       <label><b>Name: </b></label>{{r.name}}<br>
       <label><b>Ingredients: </b></label>{{r.ingredients}}<br>
       <label><b>Process: </b></label>{{r.process}}<br>
       <label><b>Recipe Image: </b></label><br>
       <img src="/media/{{r.recipe_img}}" style="width:200px;height:200px"><br><br>
<!--       <img src="{{r.recipe_img.url}}" style="width:200px;height:200px"><br>-->
{% endfor %}
<a href="{% url 'recipes:index' %}">Back</a>

recipes/templates/recipes/index.html
<div style="text-align: right">
<a href="{% url 'users:logoutpage' %}">Logout</a>
</div>

<h3>Recipes Names</h3>

{% if name_list %}
<ul>
  {% for n in name_list %}
      <li>

        <a href="{% url 'recipes:detail' n.id %}">{{ n.name }}</a>
      </li>
  {% endfor %}
</ul>
{% else %}
   <p>No Recipes are available.</p>
{% endif %}

<a href="{% url 'recipes:create' %}">Create Recipe</a>

users/templates/users/contact_form.html
<form action="/users/contact/" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

users/templates/users/login.html
<h1>Login Page</h1>
{% if message %}
{{message}}
{% endif %}
<form action="{% url 'users:dologin' %}" method="post">
  {% csrf_token %}
    <label>Email : </label><br>
    <input type="text" id="email" name="email"><br><br>
    <label>Password: </label><br>
    <input type="password" id="password" name="password"><br><br>
    <input type="submit" value="Login"><br><br>
    If New User, than <a href="{% url 'users:register' %}">Register</a> here
</form>

users/templates/users/register.html
<h1>Register Page</h1>
<form action="{% url 'users:saveuser' %}" method="post">
  {% csrf_token %}
    <label>First Name: </label><br>
    <input type="text" id="first_name" name="first_name"><br><br>
    <label>Last Name: </label><br>
    <input type="text" id="last_name" name="last_name"><br><br>
    <label>Email id: </label><br>
    <input type="email" id="email" name="email"><br><br>
    <label>Password: </label><br>
    <input type="password" id="password" name="password"><br><br>
    <label>Mobile No: </label><br>
    <input type="text" id="mobile_no" name="mobile_no"><br><br>
    <label>Date of Birth: </label><br>
    <input type="text" id="date_of_birth" name="date_of_birth"><br><br>
    <label>Age: </label><br>
    <input type="text" id="age" name="age"><br><br>
    <label>Country: </label><br>
    <input type="text" id="country" name="country"><br><br>
    <input type="submit" value="Register"><br><br>
</form>